name: Remote

on:
  workflow_dispatch:

jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install ${{ secrets.CLOUDFLARED_TOKEN }}
          sudo systemctl start cloudflared

      - name: Add 'remote' user with sudo privileges
        run: |
          sudo useradd -m code
          echo "code:${{ secrets.REMOTE_PASSWORD }}" | sudo chpasswd
          echo 'code ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/remote

      - name: Install and run forever code-server
        run: |
          sudo -H -u code bash -c 'export HOME=/home/code; curl -fsSL https://code-server.dev/install.sh | sh'
          sudo -H -u code bash -c 'export HOME=/home/code; PASSWORD=${{ secrets.REMOTE_PASSWORD }} code-server --bind-addr 0.0.0.0:8080 --auth password'
