name: Remote

on:
  workflow_dispatch:

jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install ${{ secrets.CLOUDFLARED_TOKEN }}
          sudo systemctl start cloudflared

      - name: Add 'remote' user with sudo privileges
        run: |
          sudo useradd -m remote
          echo "remote:${{ secrets.REMOTE_PASSWORD }}" | sudo chpasswd
          echo 'remote ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/remote
          sudo -u remote mkdir -p /home/runner/.config/code-server
          sudo -u remote chown -R remote:remote /home/runner/.config/code-server

      - name: Install and run forever code-server
        run: | 
          sudo -u remote curl -fsSL https://code-server.dev/install.sh | sh
          sudo -u remote PASSWORD=${{ secrets.REMOTE_PASSWORD }} code-server --bind-addr 0.0.0.0:8080 --auth password
