name: Remote

on:
  workflow_dispatch:

jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          swap-storage: false
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8
      - name: Update system
        run: |
          sudo apt update
          sudo apt upgrade -y

      
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install ${{ secrets.CLOUDFLARED_TOKEN }}
          sudo systemctl start cloudflared

      - name: Add 'remote' user with sudo privileges
        run: |
          sudo useradd -m code
          echo "code:${{ secrets.REMOTE_PASSWORD }}" | sudo chpasswd
          echo 'code ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/remote

      - name: Install and run forever code-server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          
          sudo systemctl start code-server@code
          sleep 1
          sudo systemctl stop code-server@code
          sudo -u code sed -i 's/bind-addr: 127.0.0.1:8080/bind-addr: 0.0.0.0:8080/' /home/code/.config/code-server/config.yaml
          sudo -u code sed -i 's/^password: .*/password: ${{ secrets.CODE_PASSWORD }}/' /home/code/.config/code-server/config.yaml
    
          sudo systemctl start code-server@code

      - name: Run forever
        run: while true; do sleep 60; done
