name: Remote

on:
  workflow_dispatch:

jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install ${{ secrets.CLOUDFLARED_TOKEN }}
          sudo systemctl start cloudflared
          
          sudo systemctl start ssh

      - name: Add 'remote' user with sudo privileges
        run: |
          sudo useradd -m remote
          echo "remote:${{ secrets.REMOTE_PASSWORD }}" | sudo chpasswd
          echo 'remote ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/remote

      - name: Run forever
        run: while true; do sleep 1000; done